language: node_js
node_js:
  - "8.16.0"

cache: npm

before_install:
  - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then echo "test"'
