version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:8.16.0
    steps:
      - checkout
      # special step to restore the dependency cache
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Set NPM token for private dependencies installation
          command: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      - run:
          name: Install Dependencies
          command: npm install
      # special step to save the dependency cache
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run build
          command: npm run ci-build
